### ISSUE TITLE
Pruebas de integracion no envia Detalles de servicio al API

### ISSUE THREAD

**Issue by shackra** [jdpc91/redabitsScabcr#1]
Las pruebas de integración no consigue los detalles de servicio relacionados a un comprobante y en su lugar esta enviando una lista vacía. Este problema podría deberse a la imposibilidad de crear nuevos records directamente desde los modelos para la tabla `COMPROBANTE`.

**Comment by elzorrorebelde** [comment]
primero se tiene que resolver el problema #3 para poder continuar con las pruebas y arreglar este bug

**Comment by elzorrorebelde** [comment]
resuelto en c738c4e
