### ISSUE TITLE
Enviar datos del emisor desde la API al backend

### ISSUE THREAD

**Issue by shackra** [jdpc91/redabitsScabcr#5]
En el commit b3f256f70bb83558ab5c0f119b8d3ae7429cdcd1 varios campos fueron eliminados del modelo para la tabla `COMPROBANTE` porque estos no podían ser proporcionados de alguna otra tabla en la base de datos, entre otras razones.

Durante el chat, @jdpc91 menciona que para los campos `EMISOR_IDENT_TIPO`, `EMISOR_IDENT_NUM`, `EMISOR_NOMBRE_COMERCIAL`, `EMISOR_TEL_NUM`:

> Ok yo tengo esa información en mi lado. Puedo ponerla en el response de credentials

Por el momento http://api.redabits.com/credentials.php responde con los campos `usuario`, `password`, `cert` y `pin`.

Para poder avanzar con el proyecto es necesario que los campos de `EMISOR_*` sean remitidos por la API ya sea en el API endpoint existente o en uno nuevo.

**Comment by elzorrorebelde** [comment]
@jdpc91 ha hecho los cambios necesarios en la API
